######################################################################
# Automatically generated by qmake (1.07a) Sat Dec 25 12:31:51 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += item.h starter.h
SOURCES += item.cpp main.cpp starter.cpp
