######################################################################
# Automatically generated by qmake (1.07a) Mon Dec 27 01:22:34 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += tray.h
SOURCES += main.cpp tray.cpp
