######################################################################
# Automatically generated by qmake (1.07a) Wed Dec 29 13:34:23 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += ctrlthread.h tray.h
SOURCES += ctrlthread.cpp main.cpp tray.cpp
LIBS += -lslide
