######################################################################
# Automatically generated by qmake (1.07a) Fri Dec 24 00:32:58 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += desk.h
SOURCES += desk.cpp main.cpp
